### ISSUE TITLE
Checkpoint model for the CWT

### ISSUE THREAD

**Issue by yilinliu77** [zhiheLu/CWT-for-FSS#1]
Thanks for your excellent work! 

Could you release the checkpoint model for the transformer model (CWT)?

**Comment by zhiheLu** [comment]
Sorry for replying late. Here are the checkpoints: https://drive.google.com/drive/folders/1jqLYr2fwTMr9lfDsoQoW13Q3WkfUZVn6?usp=sharing, for the transformer with the setting: `1-shot, ResNet-50, PASCAL dataset`. Will release more models later.
