### ISSUE TITLE
training ppm by myself

### ISSUE THREAD

**Issue by AI4Math-ShanZhang** [zhiheLu/CWT-for-FSS#4]
hi, thanks for this good job! can u advice me how to train the ppm by my self, instead of load your model weights.

**Comment by zhiheLu** [comment]
This code may help you: https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation

**Comment by AI4Math-ShanZhang** [comment]
Thanks for your reply, when I lode the weights you provided and train the CWT, the max Miou achieves the largest 54.4% on 5 epochs, and then no increasing trend but decreasing during next epochs training. Can u give me some advice about that?
