### ISSUE TITLE
Pascal SegmentationClassAug dataset

### ISSUE THREAD

**Issue by tt622** [zhiheLu/CWT-for-FSS#7]
Thank you for your work!
I have a question about Pascal dataset. I have downloaded the official dataset of Pascal. But i didn't find the SegmentationClassAug dataset which was used in the code. How can I get this dataset? Thanks!

**Comment by zhiheLu** [comment]
You can download the data from this link: https://drive.google.com/drive/folders/1N00R9m9qe2rKZChZ8N7Hib_HR2HGtXHp.
