### ISSUE TITLE
how to generate SegmentationClassAug？

### ISSUE THREAD

**Issue by WHL182** [zhiheLu/CWT-for-FSS#8]
I have downloaded the PASCAL VOC 2012 dataset and SBD dataset from their official website respectively.But I donnot know how to use them in the code .Could you show me your dataset folder structure or the method to generate SegmentationClassAug?
Thanks , bubble from hfut!

**Comment by zhiheLu** [comment]
You can download the data from this link: https://drive.google.com/drive/folders/1N00R9m9qe2rKZChZ8N7Hib_HR2HGtXHp.
