### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by LIUYUANWEI98** [zhiheLu/CWT-for-FSS#9]
Thanks for your released code. However, in your paper and code, there are no detailed description about the training of pre-trained model. Are you choose the task of classification or segmentation for pre-training process？ If segmentation, how can you construct the image-label pairs?

**Comment by zhiheLu** [comment]
You can refer to this code: https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation for pre-training part.
